language: android
sudo: false
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.3

    # The SDK version used to compile your project
    - android-30

    - extra-android-m2repository
    - extra-google-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-30
    - sys-img-x86-android-26

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager tools
  - yes | sdkmanager "system-images;android-30;google_apis;x86_64"

install:
  - true

before_script:
  - echo no | android create avd --force -n test -k "system-images;android-30;google_apis;x86_64"
  - cd $(dirname $(which emulator)) && ./emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
# go and test other modules before going on to app, can only have one travis file per repo.
- cd dmz && ../gradlew -i build && ../gradlew -i test && cd ..
- cd lib && ../gradlew -i build && ../gradlew -i test && cd ..
- cd util && ../gradlew -i build && ../gradlew -i test && cd ..
- ./gradlew test
- ./gradlew uninstallAll connectedAndroidTest
- ./gradlew build -x test

after_success:
 - bash <(curl -s https://codecov.io/bash)
