name: Comments Android lint warnings on pull request
on: pull_request
jobs:
  lint:
    name: Comments lint result on PR
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      - name: Run detekt
        run: ./gradlew :app:detekt
        continue-on-error: true
      - name: Run Android Lint
        run: ./gradlew :app:lintAnalyticsDebug
      - name: Run Android Lint Reporter to report Lint and Detekt result to PR
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew report -PgithubPullRequestId=$PR_NUMBER -PgithubToken=$GITHUB_TOKEN