name: Android lint

on: [push, pull_request]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      - name: Run detekt
        run: ./gradlew :app:detekt
        continue-on-error: true
      - name: Run Android Lint
        run: ./gradlew :app:lintNoAnalyticsDebug
      - name: Run Android Lint Reporter to report Lint and Detekt result to PR
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew report -PgithubPullRequestId=$PR_NUMBER -PgithubToken=$GITHUB_TOKEN